### ISSUE TITLE
Issue with BNO080

### ISSUE THREAD

**Issue by CalebVaccaro** [BBUK/Bell-Boy#2]
We are having trouble connecting the I2C with the rPI. We need help with reading data from the sensor from the I2C. Can we pm you?

**Comment by BBUK** [comment]
The BNO080 needs I2C clock stretching which the Pi does not do so well.  See here: [https://www.raspberrypi.org/forums/viewtopic.php?t=234577](url) .  This is why I used SPI.  I wonder if this is the problem you are experiencing...

**Comment by CalebVaccaro** [comment]
The link is not working. Do you think its still a viable option to use the Pi. We just need quats off the sensor. If not, have you worked with better options for IMUs (components that could accomplish the same goal). Thanks for the reply

Would you know of an SPL library for it?

Parts List:
Qwiic VR IMU (BNO080)
Qwiic pHAT v2.0
Rasberry pi 4

**Comment by BBUK** [comment]
Sorry, try this [link](https://www.raspberrypi.org/forums/viewtopic.php?t=234577).  I don't know for sure but I think the Qwiic connectors only use I2C.  I also don't know if the Pi I2C clock stretching bug is still there in the Pi4.

If I2C is a problem then that board can use SPI, you just need to wire the Pi to the SPI pins.  See [issue 1](https://github.com/BBUK/Bell-Boy/issues/1), to see someone who did just that with the same board with success using the code here.
