### ISSUE TITLE
RST in old BNO080-general.c

### ISSUE THREAD

**Issue by mdgc3** [BBUK/Bell-Boy#3]
Good afternoon,
I am fairly new at mechatronics and am working to use SPI with a BNO080. I thought I followed your instructions correctly (yes I tried to make sure I plugged in the correct pins since they are BCM pins), but it keeps getting stuck on "device did not wake on reset". I do not know if it is a wiring issue or because I have a Raspberry Pi 4B and you were using a Raspberry Pi Zero, or if something else is going on. I have attached photos and would really really appreciate some help. 
[edit- I saw in your past issues you had a similar question. My wiring is the same I think, but I changed the usleep in line 819 to 10000 just in case. I have also tried plugging in the RST wire on both of the options on the BNO080 from sparkfun]

Below is my wiring: (sorry about color repeats I didn't have a ton of wires)
![IMG_1860](https://user-images.githubusercontent.com/83476148/122613122-4b0d7180-d052-11eb-8483-6d239f65dca5.jpeg)
![IMG_1861](https://user-images.githubusercontent.com/83476148/122613128-506abc00-d052-11eb-88dc-c4aaebaf8dcb.jpeg)

![IMG_1859](https://user-images.githubusercontent.com/83476148/122611649-ae49d480-d04f-11eb-8ed0-1a216c2681f3.jpeg)

Thank you for your patience,
mdgc3

**Comment by mdgc3** [comment]
I seem to have gotten it to work once, but then I upgraded my raspberry pi on the command line and it does not work again. 

Also what is a continuation????

**Comment by BBUK** [comment]
I see you still have the pull-up resistors connected.  They are only used for i2c.  According to this: https://cdn.sparkfun.com/assets/5/c/c/8/8/SparkFun_Qwiic_VR_IMU_Breakout.pdf the jumper should be cleared (both sides) for SPI usage.  Also, have you set PS0 and PS1 correctly?

**Comment by mdgc3** [comment]
I saw you talked about that and eventually cleared the jumper (you mean desoldering the i2c thing, right?). 
Also, I soldered the PS0 and PS1 on the other side of the board because the datasheet said they both had to be at 1 to be in SPI mode

The issue is I downloaded circuitpython to try this SPI communication using that, and it just stopped working again.

Below is a picture of the only time I got it to work
<img width="518" alt="Screen Shot 2021-07-07 at 4 49 43 PM" src="https://user-images.githubusercontent.com/83476148/124826875-59f58e80-df43-11eb-814b-f38ea5d66c56.png">

Also I assume this is also a rookie question, but aren't there only supposed to be 4 connecting wires (plus the power and ground?)

**Comment by mdgc3** [comment]
I always get the following response: 
"Cannot communicate with BNO080: got 00 DATALENGTH 0001"

I am reading and looking at what u sent me, but I cannot tell what I am doing wrong. This is currently my wiring:
<img width="487" alt="Screen Shot 2021-07-07 at 5 12 22 PM" src="https://user-images.githubusercontent.com/83476148/124829346-82cb5300-df46-11eb-801b-3f77773328a9.png">

**Comment by BBUK** [comment]
Are you *sure* that the i2c jumper is cleared?  What you are seeing looks like a bad connection but it could also be caused by the i2c pull-ups.

As a trial, try reducing the speed of the SPI link.  To do that change:
`bcm2835_spi_set_speed_hz(3000000);`
to
`bcm2835_spi_set_speed_hz(1000000);`

**Comment by mdgc3** [comment]
Okay so I reconnected all the wires to follow the schematic below:
<img width="605" alt="Screen Shot 2021-07-07 at 6 48 37 PM" src="https://user-images.githubusercontent.com/83476148/124838728-713d7780-df55-11eb-8dc2-6da1ab102432.png">

I ran it various times and it said "reset packet not received" each time.
Then I tried changing the line you suggested and then it said "device did not wake on reset" sometimes, but otherwise it is the "reset packet not received"

...i'm back at square 1

**Comment by BBUK** [comment]
Wiring looks OK.

Try taking the SPI frequency down further:
`bcm2835_spi_set_speed_hz(500000);`
And let me know what you see...

**Comment by mdgc3** [comment]
It gave me the same result. I'll check tomorrow if there is still solder on the i2c port. But to confirm, I am not supposed to plug in anything else?
I think the issue is occurring during collectPacket(), but I honestly don't know what else it could be. I wish I had not updated and upgraded my raspberry pi.

**Comment by BBUK** [comment]
Before I try to replicate this, would you please try to add:
`total_mem=1024`
in config.txt (and reboot).  I can see that there is something different in how SPI works on the 4B related to DMA access to higher memory areas (and the bcm2835 library uses DMA, if I recall).

Also check for any SPI-related entries in your config.txt and let me know if there are any there.

**Comment by mdgc3** [comment]
Okay I did not know how to make that happen but apparently you can check with "vcgencmd get_config int", and in the photo (below) it says the memory is correct. I did not know how to find the spi info.
<img width="483" alt="Screen Shot 2021-07-08 at 9 59 39 PM" src="https://user-images.githubusercontent.com/83476148/125012253-e4b7b580-e037-11eb-8f1e-b4cd375b7c29.png">

 
Also since I was worried it broke due to the circuitpython installation, I tried an extra SD card that had the same formatting as the other one did before. I redownloaded your git and the 1.68 version (newest) version of the BCM library thing. But it did the same "did not wake on reset"/"reset package not received" as usual. So I checked those settings as well. 
<img width="450" alt="Screen Shot 2021-07-08 at 9 59 50 PM" src="https://user-images.githubusercontent.com/83476148/125012246-e1bcc500-e037-11eb-8052-21c47e84ac73.png">

**Comment by BBUK** [comment]
Hi again.  I was trying to get you to *reduce* the amount of memory available to your Pi4 on a temporary basis.  To do this you need to edit config.txt (`sudo nano /boot/config.txt`) so that you add the total_mem line.  The end of the file should then look like:

`[pi4]`
`# Enable DRM VC4 V3D driver on top of the dispmanx display stack`
`dtoverlay=vc4-fkms-v3d`
`max_framebuffers=2`
`total_mem=1024`
`[all]`
`# dtoverlay=vc4-fkms-v3d`

I hope you know how to use nano!

**Comment by mdgc3** [comment]
Okay so I resoldered the PS1 and PS0 chips. I also removed as much solder as I could on the I2C jumper. 
Then I followed your instructions and added the total_mem line but it is still not working (printing the same 2 lines)

**Comment by BBUK** [comment]
OK, I will try to replicate here (give me a few days).

While you are waiting - do you have a multimeter? If yes, please would you check the resistance between SO and 3V3 and between SCK and 3V3 (disconnect SO and SCK from the Pi first).

**Comment by mdgc3** [comment]
I have a multimeter! And I can check it. 
Is there any chance we can videochat?

**Comment by BBUK** [comment]
I will have to politely decline the videochat!

Also please do not send me (more) money, this is supposed to be a hobby for me.

**Comment by mdgc3** [comment]
That is completely understandable. And yeah that makes sense, I just feel bad wasting your time. 

Here is what my multimeter measured.
The 3.3 to SO:
<img width="508" alt="Screen Shot 2021-07-09 at 4 27 41 PM" src="https://user-images.githubusercontent.com/83476148/125132769-cbb01280-e0d2-11eb-937b-552585d95d9c.png">

The 3.3 to SCK:
<img width="499" alt="Screen Shot 2021-07-09 at 4 27 33 PM" src="https://user-images.githubusercontent.com/83476148/125132762-c8b52200-e0d2-11eb-8397-32a487bcef4e.png">

I did notice in a past question, someone talked about their wiring and from what I read it looks more like this:
<img width="559" alt="Screen Shot 2021-07-09 at 4 06 25 PM" src="https://user-images.githubusercontent.com/83476148/125130890-cd2c0b80-e0cf-11eb-864e-28a6281817d5.png">

Could this be the reason? Because I know the PS0 and PS1 are supposed to be 1, so I don't know if I am supposed to ALSO connect them, not just solder the jumpers

**Comment by BBUK** [comment]
It looks like the SCK side of the i2c solder pads is still connected (probably a tiny solder bridge).  You should be able to see it under a magnifying glass or feel it by running a pin (or something sharp) on each side of the central pad (I don't know without checking which of the two outer pads is connected to SCK.  It is best to use solder wick to clean the bridge (but there are other ways).

**Comment by mdgc3** [comment]
Okay I did the solder removing again with the solder wick:
<img width="323" alt="Screen Shot 2021-07-09 at 5 47 13 PM" src="https://user-images.githubusercontent.com/83476148/125139924-69a9da00-e0df-11eb-9826-b5e02976c773.png">

Here is a picture of the resistance now:
<img width="513" alt="Screen Shot 2021-07-09 at 5 47 22 PM" src="https://user-images.githubusercontent.com/83476148/125139932-70385180-e0df-11eb-9641-8a90eaa042b5.png">

Unfortunately it is still not working :(

**Comment by mdgc3** [comment]
In collectPacket(), line 877 seems to be the error. Are lines 861/862 (peri_set_bits) sending packets to the IMU that would cause it to send back a reset signal?

**Comment by BBUK** [comment]
collectPacket() could easily act strangely if it is reading junk because other things are not working correctly.  

I can see errors in your wiring.  You have connected the chip enable (yellow) to GPIO24 when it should be connected to (physical) PIN24 (marked as CE0 on the Cobbler).  You have connected Wake (white) to GPIO22 when it should be connected to physical PIN22 (which is GPIO25 and marked #25). Also, what have you connected to GPIO18 (physical PIN12)?  I think you intended to put that into GPIO24 which is physical PIN18 (marked #24 on the cobbler)?  I may not be able to see everything well from the picture so check your wiring carefully - your wiring diagram above is correct (and you shouldn't need to connect PS0/PS1 as long as those pads are soldered) - replicate that diagram with the Cobbler and let me know what you see.

If it helps with your wiring see the first image on this page [https://www.raspberrypi.org/documentation/usage/gpio/](url) which shows the differences between GPIO numbers and physical pin numbers.   In my code I use GPIO numbers and the cobbler seems to do the same.

**Comment by mdgc3** [comment]
Good morning, I apologize for the delay in response. I was out of town. I did not realize I wired it wrong when I changed into the cobbler but I appreciate it. Now I got it to read!
<img width="459" alt="Screen Shot 2021-07-12 at 1 11 18 PM" src="https://user-images.githubusercontent.com/83476148/125328754-b0334a80-e312-11eb-987c-2143dc9a0b82.png">
Thank you so much :)

**Comment by mdgc3** [comment]
It was running at 50000 Hz, so I tried 3000000 Hz and it printed "cannot communicate with BNO080: got 03 DATALENGTH 0002". So then I tried 2000000 Hz and it seems slower but at least it runs.

**Comment by BBUK** [comment]
Glad to hear that you have it working.

Take the SPI clock rate to as high as it can go whilst working reliably.  You have some pretty long wires there with multiple connections and it is expected that the SPI clock will not be able to operate at the full 3MHz.  2MHz may be too high still (the slowness may simply be a function of only being able to read occasionally).  Try 1.5MHz or even 1MHz.

Also, don't forget to take the `total_mem=1024` line out of config.txt.

BBUK

**Comment by mdgc3** [comment]
Thank you so so so much!!!
Yeah it makes sense, I will fiddle with it a bit. Thank you once again!
